
image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw install -DskipTests=false -Ddockerfile.skip

ports:
  - port: 8443
    visibility: public
    onOpen: open-browser
  - port: 5672
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack
